#!/usr/bin/env python3
"""Generate a separate compressed browser candidate; leave the old file intact."""
from pathlib import Path
import re, json, hashlib
HERE=Path(__file__).resolve().parent
ROOT=HERE.parent
LEAN=ROOT/'lean'
OLD=HERE/'ThreeSquaresLean4Web.lean'
OUT=HERE/'ThreeSquaresCompressed.lean'
visited=set()
ordered=[]

def visit(name):
    if name in visited:return
    visited.add(name)
    path=LEAN.joinpath(*name.split('.')).with_suffix('.lean')
    source=path.read_text()
    for dep in re.findall(r'^import\s+([\w.]+)',source,re.M):
        if dep.startswith('ThreeSquares'):visit(dep)
    ordered.append((name,path,source))

def private_names(source,module):
    prefix='fw'+module.replace('.','_')
    regex=r"(?m)^private\s+(?:(?:noncomputable|unsafe)\s+)*(?:theorem|lemma|def|abbrev|opaque|inductive|structure)\s+([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)"
    for name in re.findall(regex,source):
        if '.' in name:
            ns,short=name.rsplit('.',1);replacement=ns+'.'+prefix+'_'+short
        else:replacement=prefix+'_'+name
        source=re.sub(r"(?<![A-Za-z0-9_'])"+re.escape(name)+r"(?![A-Za-z0-9_'])",replacement,source)
        if '.' in name:
            # Dot notation can refer to a private declaration as `C.weight_pos`.
            source=re.sub(r"(?<![A-Za-z0-9_'])"+re.escape(short)+r"(?![A-Za-z0-9_'])",
                          prefix+'_'+short,source)
    return source

def main():
    frozen=hashlib.sha256(OLD.read_bytes()).hexdigest()
    visit('ThreeSquares.Compressed.Main')
    imports=['Mathlib.Analysis.InnerProductSpace.PiL2', 'Mathlib.Analysis.LocallyConvex.Separation', 'Mathlib.Analysis.Normed.Affine.MazurUlam', 'Mathlib.Analysis.Normed.Group.AddTorsor', 'Mathlib.Analysis.Normed.Module.FiniteDimension', 'Mathlib.Analysis.SpecialFunctions.Sqrt', 'Mathlib.Data.Fin.VecNotation', 'Mathlib.Data.Real.Basic', 'Mathlib.Geometry.Euclidean.Basic', 'Mathlib.Tactic.FinCases', 'Mathlib.Tactic.FunProp', 'Mathlib.Tactic.Linarith', 'Mathlib.Tactic.NormNum', 'Mathlib.Tactic.Positivity', 'Mathlib.Tactic.Ring']
    imports=sorted(set(imports+['Mathlib.Tactic.LinearCombination', 'Mathlib.Tactic.FieldSimp',
        'Mathlib.Tactic.Tauto', 'Mathlib.Tactic.ByContra', 'Mathlib.Tactic.Push', 'Mathlib.Tactic.SplitIfs',
        'Mathlib.Tactic.Ext', 'Mathlib.Tactic.Convert']))
    old=OLD.read_text()
    # The old edition's header embeds exactly the four pinned FC definitions.
    definitions=old[old.index('open EuclideanGeometry'):old.index('/-! Lean4Web source module:')]
    header='\n'.join('import '+x for x in imports)+'''

/-! Compressed three-square proof. Generated by
`lean4web/generate_compressed.py`.
FC commit: 8927a585c5d522fc132d7ea6488fcd9e30ccd80e.
The four FC definitions below are embedded for the single-file web edition.
The Lake target `ThreeSquares.Compressed.Main` imports the actual FC module.
Final audit: ThreeSquares.CenterElimination.Compressed.least_three_square_packing_in_circle.
-/
set_option autoImplicit false
set_option Elab.async false
'''+definitions
    chunks=[header]
    for name,path,source in ordered:
        if name == 'ThreeSquares.Compressed.EditorInfo':
            continue
        source = source.replace('set_option linter.unusedTactic false\n', '')
        source = source.replace('set_option linter.unreachableTactic false\n', '')
        source=re.sub(r'^import[^\n]*\n','',source,flags=re.M)
        source=private_names(source,name)
        chunks.append(f'\n/-! Source: `{name}`. -/\n'+source)
        if name=='ThreeSquares.Compressed.Bridge':
            # Close the top-level noncomputable section used by this file.
            chunks.append('end\n')
        if m:=re.fullmatch(r'ThreeSquares\.Compressed\.Part(\d+)',name):
            i=int(m[1])+1
            chunks.append(f'#print "Compressed certificate group {i}/16 complete; final audit still required."\n')
    src='\n'.join(chunks)
    # Keep normal metadata for the common geometry, omitting only the generated
    # certificate declarations' intermediate editor states. Do not suppress errors.
    editor_source=(LEAN/'ThreeSquares/Compressed/EditorInfo.lean').read_text()
    editor_code=editor_source[editor_source.index('open Lean Elab Command in'):]
    helper='-- Certificate declarations omit intermediate editor metadata. Kernel checks remain enabled.\n'+editor_code
    helper+='set_option linter.unusedTactic false\nset_option linter.unreachableTactic false\n'
    where=src.index('/-! Source: `ThreeSquares.Compressed.Part00`. -/')
    src=src[:where]+helper+src[where:]
    # Optional local-version edition for validation, without changing the web target.
    import argparse
    p=argparse.ArgumentParser();p.add_argument('--local-output',type=Path);args=p.parse_args()
    if args.local_output:
        args.local_output.write_text(src)
    aliases={'if_pos':'ite_eq_left','if_neg':'ite_eq_right','if_true':'ite_true','if_false':'ite_false'}
    web=re.sub(r"(?<![A-Za-z0-9_'])\b(?:if_pos|if_neg|if_true|if_false)\b(?![A-Za-z0-9_'])",
               lambda m:aliases[m[0]],src)
    OUT.write_text(web)
    assert hashlib.sha256(OLD.read_bytes()).hexdigest()==frozen
    web_sha=hashlib.sha256(web.encode()).hexdigest()
    browser_evidence=ROOT/'lean/verification/compressed/browser-observation.json'
    browser_observed=False
    if browser_evidence.exists():
        observation=json.loads(browser_evidence.read_text())
        browser_observed=(observation.get('local_generated_source_sha256')==web_sha
                          and observation.get('browser_toolchain_shown')=='Lean v4.35.0-rc2'
                          and 'least_three_square_packing_in_circle'
                              in observation.get('final_axioms_shown',{}))
    result=dict(candidate=str(OUT),sha256=web_sha,
                bytes=len(web.encode()),lines=web.count('\n'),modules=len(ordered),
                old_artifact_sha256_unchanged=frozen,target_version='4.35.0-rc2',
                v435_browser_final_audit_user_observed=browser_observed,
                v435_browser_evidence='lean/verification/compressed/browser-observation.json' if browser_observed else None,
                sources={str(path.relative_to(ROOT)):hashlib.sha256(path.read_bytes()).hexdigest()
                         for _,path,_ in ordered})
    (HERE/'compressed-source-manifest.json').write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps({k:v for k,v in result.items() if k!='sources'},indent=2))

if __name__=='__main__':main()
