import ThreeSquares.WeightedSearch
import ThreeSquares.ContractedSyntax
import Lean.Data.Json

open ThreeSquares
open ThreeSquares.PackingFormula

/-! Run with `lake env lean --run GenerateCertificates.lean` from the project root.
The executable proposes data only. Generated theorems independently reduce the
checker in the kernel. All formulas come from the same source as the FC bridge. -/

structure Case where
  name : String
  domain : String
  box : RationalBox 15
  formulaName : String
  depth : Nat
  weighted : Bool

def slide (s right : ℚ) : RationalBox 15 :=
  ![⟨-1, 0⟩, .singleton 0, .singleton right, .singleton (-1 / 2),
    .singleton right, .singleton (1 / 2),
    .singleton 1, .singleton 0, .singleton 0, .singleton 1,
    .singleton 1, .singleton 0, .singleton 0, .singleton 1, .singleton s]

def nearContact : RationalBox 15 :=
  ![⟨-23 / 32, -21 / 32⟩, ⟨-1 / 32, 1 / 32⟩,
    ⟨9 / 32, 11 / 32⟩, ⟨-17 / 32, -15 / 32⟩,
    ⟨9 / 32, 11 / 32⟩, ⟨15 / 32, 17 / 32⟩,
    ⟨31 / 32, 1⟩, ⟨-1 / 32, 1 / 32⟩, ⟨-1 / 32, 1 / 32⟩, ⟨31 / 32, 1⟩,
    ⟨31 / 32, 1⟩, ⟨-1 / 32, 1 / 32⟩, ⟨-1 / 32, 1 / 32⟩, ⟨31 / 32, 1⟩,
    ⟨13 / 8, 425 / 256⟩]

def rotatedOverlap : RationalBox 15 :=
  fun i => if i.val < 6 then
    (if i.val % 2 == 0 then ⟨-1 / 2, 1 / 2⟩ else ⟨-1 / 8, 1 / 8⟩)
  else nearContact i

def cases : List Case := [
  ⟨"Subcritical3", "axis-aligned slice; x0 in [-1,0]; x1=x2=1/4; s=13/8", slide (13 / 8) (1 / 4), "smallerFormula", 3, false⟩,
  ⟨"Subcritical5", "axis-aligned slice; x0 in [-1,0]; x1=x2=1/4; s=13/8", slide (13 / 8) (1 / 4), "smallerFormula", 5, false⟩,
  ⟨"Subcritical7", "axis-aligned slice; x0 in [-1,0]; x1=x2=1/4; s=13/8", slide (13 / 8) (1 / 4), "smallerFormula", 7, false⟩,
  ⟨"Contact5", "axis-aligned slice; x0 in [-1,0]; s=425/256", slide (425 / 256) (5 / 16), "formula", 5, false⟩,
  ⟨"Contact8", "axis-aligned slice; x0 in [-1,0]; s=425/256", slide (425 / 256) (5 / 16), "formula", 8, false⟩,
  ⟨"Rotated6", "15-variable neighborhood of canonical contact; rotations retained", nearContact, "smallerFormula", 6, false⟩,
  ⟨"RotatedOverlap6", "rotatable frames near identity; centers in [-1/2,1/2] x [-1/8,1/8]", rotatedOverlap, "smallerFormula", 6, false⟩,
  ⟨"Initial6", "full initial box [-2,2]^15; bounded search only", initialBox, "smallerFormula", 6, false⟩,
  ⟨"Contracted6", "all smaller FC packings in contractedBox; original constraints", contractedBox, "smallerFormula", 6, false⟩,
  ⟨"Strengthened6", "contractedBox; added center disks, distances and radial bounds", contractedBox, "contractedFormula", 6, false⟩,
  ⟨"Focused6", "contractedBox and necessary conditions; center weights 4", contractedBox, "contractedFormula", 6, true⟩,
  ⟨"Focused8", "contractedBox and necessary conditions; center weights 4", contractedBox, "contractedFormula", 8, true⟩]

def ratSource (q : ℚ) : String := s!"({q.num} / {q.den})"

def boxSource (B : RationalBox 15) : String :=
  "![" ++ String.intercalate ",\n    " ((List.finRange 15).map fun i =>
    "⟨" ++ ratSource (B i).lo ++ ", " ++ ratSource (B i).hi ++ "⟩") ++ "]"

def treeSource : IntervalCertificate 15 → String
  | .reject => ".reject"
  | .keep => ".keep"
  | .split i q l r => s!"(.split {i.val} {ratSource q} {treeSource l} {treeSource r})"

def boxJson (B : RationalBox 15) : Lean.Json :=
  Lean.toJson ((List.finRange 15).map fun i => [toString (B i).lo, toString (B i).hi])

def main : IO Unit := do
  let mut reports : Array Lean.Json := #[]
  let mut imports : Array String := #[]
  for c in cases do
    let p ← match c.formulaName with
      | "formula" => pure formula
      | "smallerFormula" => pure smallerFormula
      | "contractedFormula" => pure contractedFormula
      | other => throw (IO.userError s!"Unknown formula: {other}")
    let started ← IO.monoNanosNow
    let treeRef ← IO.mkRef (if c.weighted then
      IntervalCertificate.searchWeighted packingSearchWeights p c.box c.depth
      else IntervalCertificate.search p c.box c.depth)
    let t ← treeRef.get
    let statsRef ← IO.mkRef (t.nodeCount, t.keptCount, t.rejectedCount, t.depth)
    let (nodes, kept, rejected, actualDepth) ← statsRef.get
    let generated ← IO.monoNanosNow
    let checkRef ← IO.mkRef (t.check p c.box)
    let accepted ← checkRef.get
    let checked ← IO.monoNanosNow
    unless accepted do throw (IO.userError s!"Generator produced invalid tree: {c.name}")
    let f := c.formulaName
    let mut source := "import ThreeSquares.WeightedSearch\nimport ThreeSquares.ContractedSyntax\n\n"
    source := source ++ "-- Generated by GenerateCertificates.lean; kernel-checked data, not a global proof.\n"
    source := source ++ s!"namespace ThreeSquares.GeneratedCertificates.{c.name}\n\nopen PackingFormula\n\n"
    source := source ++ "set_option maxRecDepth 20000\nset_option maxHeartbeats 4000000\n\n"
    source := source ++ s!"def box : RationalBox 15 :=\n  {boxSource c.box}\n\ndef certificate : IntervalCertificate 15 :=\n  {treeSource t}\n\n"
    source := source ++ s!"theorem accepted : certificate.check {f} box = true := by\n  decide +kernel\n\n"
    source := source ++ s!"theorem statistics : certificate.nodeCount = {nodes} ∧ certificate.keptCount = {kept} ∧\n    certificate.rejectedCount = {rejected} ∧ certificate.depth = {actualDepth} := by\n  decide +kernel\n\n"
    source := source ++ "theorem localizes {x : Fin 15 → ℝ} (hx : box.Contains x) (hp : " ++ s!"{f}.Holds x) :\n    ∃ C ∈ certificate.residuals box, C.Contains x :=\n  certificate.check_sound {f} accepted hx hp\n\n"
    if kept == 0 then
      source := source ++ s!"theorem infeasible : ¬ ∃ x : Fin 15 → ℝ, box.Contains x ∧ {f}.Holds x := by\n  apply certificate.exclude_sound {f} accepted\n  exact List.length_eq_zero_iff.mp ((certificate.residuals_length box).trans statistics.2.1)\n\n"
    source := source ++ s!"end ThreeSquares.GeneratedCertificates.{c.name}\n"
    let file := s!"ThreeSquares/GeneratedCertificates/{c.name}.lean"
    IO.FS.writeFile file source
    IO.FS.writeFile s!"certificates/{c.name}-residuals.json"
      (Lean.Json.pretty (Lean.toJson ((t.residuals c.box).map boxJson)) ++ "\n")
    imports := imports.push s!"import ThreeSquares.GeneratedCertificates.{c.name}"
    let report := Lean.Json.mkObj [
      ("case", Lean.toJson c.name), ("domain", Lean.toJson c.domain),
      ("formula", Lean.toJson f), ("depth_limit", Lean.toJson c.depth),
      ("center_weight", Lean.toJson (if c.weighted then (4 : Nat) else 1)),
      ("node_count", Lean.toJson nodes), ("kept_count", Lean.toJson kept),
      ("rejected_count", Lean.toJson rejected), ("actual_depth", Lean.toJson actualDepth),
      ("generation_ns", Lean.toJson (generated - started)),
      ("compiled_check_ns", Lean.toJson (checked - generated)),
      ("compiled_check_accepted", Lean.toJson accepted),
      ("source_file", Lean.toJson file), ("source_bytes", Lean.toJson source.utf8ByteSize)]
    reports := reports.push report
    IO.println report.compress
  IO.FS.writeFile "ThreeSquares/GeneratedCertificates.lean" (String.intercalate "\n" imports.toList ++ "\n")
  IO.FS.writeFile "certificates/generation.json" ((Lean.toJson reports).pretty ++ "\n")
