import ThreeSquares.WeightedSearch
import ThreeSquares.ContractedSyntax

-- Generated by GenerateCertificates.lean; kernel-checked data, not a global proof.
namespace ThreeSquares.GeneratedCertificates.Contact5

open PackingFormula

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

def box : RationalBox 15 :=
  ![⟨(-1 / 1), (0 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(5 / 16), (5 / 16)⟩,
    ⟨(-1 / 2), (-1 / 2)⟩,
    ⟨(5 / 16), (5 / 16)⟩,
    ⟨(1 / 2), (1 / 2)⟩,
    ⟨(1 / 1), (1 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(1 / 1), (1 / 1)⟩,
    ⟨(1 / 1), (1 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(1 / 1), (1 / 1)⟩,
    ⟨(425 / 256), (425 / 256)⟩]

def certificate : IntervalCertificate 15 :=
  (.split 0 (-1 / 2) (.split 0 (-3 / 4) .reject (.split 0 (-5 / 8) (.split 0 (-11 / 16) (.split 0 (-23 / 32) .reject .keep) (.split 0 (-21 / 32) .keep .reject)) .reject)) .reject)

theorem accepted : certificate.check formula box = true := by
  decide +kernel

theorem statistics : certificate.nodeCount = 13 ∧ certificate.keptCount = 2 ∧
    certificate.rejectedCount = 5 ∧ certificate.depth = 5 := by
  decide +kernel

theorem localizes {x : Fin 15 → ℝ} (hx : box.Contains x) (hp : formula.Holds x) :
    ∃ C ∈ certificate.residuals box, C.Contains x :=
  certificate.check_sound formula accepted hx hp

end ThreeSquares.GeneratedCertificates.Contact5
