import ThreeSquares.WeightedSearch
import ThreeSquares.ContractedSyntax

-- Generated by GenerateCertificates.lean; kernel-checked data, not a global proof.
namespace ThreeSquares.GeneratedCertificates.Focused6

open PackingFormula

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

def box : RationalBox 15 :=
  ![⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(1 / 2), (425 / 256)⟩]

def certificate : IntervalCertificate 15 :=
  (.split 0 (0 / 1) (.split 1 (0 / 1) (.split 2 (0 / 1) (.split 3 (0 / 1) .reject (.split 4 (0 / 1) (.split 5 (0 / 1) .reject .reject) (.split 5 (0 / 1) .keep .keep))) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .reject .keep) (.split 5 (0 / 1) .reject .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .reject .keep) (.split 5 (0 / 1) .keep .reject)))) (.split 2 (0 / 1) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .reject .reject) (.split 5 (0 / 1) .keep .keep)) .reject) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .reject) (.split 5 (0 / 1) .reject .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .reject) (.split 5 (0 / 1) .keep .reject))))) (.split 1 (0 / 1) (.split 2 (0 / 1) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .reject .keep) (.split 5 (0 / 1) .reject .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .reject) (.split 5 (0 / 1) .reject .keep))) (.split 3 (0 / 1) .reject (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .reject .reject)))) (.split 2 (0 / 1) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .reject .keep) (.split 5 (0 / 1) .keep .reject)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .reject) (.split 5 (0 / 1) .keep .reject))) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .reject .reject)) .reject))))

theorem accepted : certificate.check contractedFormula box = true := by
  decide +kernel

theorem statistics : certificate.nodeCount = 103 ∧ certificate.keptCount = 24 ∧
    certificate.rejectedCount = 28 ∧ certificate.depth = 6 := by
  decide +kernel

theorem localizes {x : Fin 15 → ℝ} (hx : box.Contains x) (hp : contractedFormula.Holds x) :
    ∃ C ∈ certificate.residuals box, C.Contains x :=
  certificate.check_sound contractedFormula accepted hx hp

end ThreeSquares.GeneratedCertificates.Focused6
