import ThreeSquares.WeightedSearch
import ThreeSquares.ContractedSyntax

-- Generated by GenerateCertificates.lean; kernel-checked data, not a global proof.
namespace ThreeSquares.GeneratedCertificates.Initial6

open PackingFormula

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

def box : RationalBox 15 :=
  ![⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩,
    ⟨(-2 / 1), (2 / 1)⟩]

def certificate : IntervalCertificate 15 :=
  (.split 0 (0 / 1) (.split 1 (0 / 1) (.split 2 (0 / 1) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep))) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)))) (.split 2 (0 / 1) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep))) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep))))) (.split 1 (0 / 1) (.split 2 (0 / 1) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep))) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)))) (.split 2 (0 / 1) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep))) (.split 3 (0 / 1) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep)) (.split 4 (0 / 1) (.split 5 (0 / 1) .keep .keep) (.split 5 (0 / 1) .keep .keep))))))

theorem accepted : certificate.check smallerFormula box = true := by
  decide +kernel

theorem statistics : certificate.nodeCount = 127 ∧ certificate.keptCount = 64 ∧
    certificate.rejectedCount = 0 ∧ certificate.depth = 6 := by
  decide +kernel

theorem localizes {x : Fin 15 → ℝ} (hx : box.Contains x) (hp : smallerFormula.Holds x) :
    ∃ C ∈ certificate.residuals box, C.Contains x :=
  certificate.check_sound smallerFormula accepted hx hp

end ThreeSquares.GeneratedCertificates.Initial6
