import ThreeSquares.WeightedSearch
import ThreeSquares.ContractedSyntax

-- Generated by GenerateCertificates.lean; kernel-checked data, not a global proof.
namespace ThreeSquares.GeneratedCertificates.RotatedOverlap6

open PackingFormula

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

def box : RationalBox 15 :=
  ![⟨(-1 / 2), (1 / 2)⟩,
    ⟨(-1 / 8), (1 / 8)⟩,
    ⟨(-1 / 2), (1 / 2)⟩,
    ⟨(-1 / 8), (1 / 8)⟩,
    ⟨(-1 / 2), (1 / 2)⟩,
    ⟨(-1 / 8), (1 / 8)⟩,
    ⟨(31 / 32), (1 / 1)⟩,
    ⟨(-1 / 32), (1 / 32)⟩,
    ⟨(-1 / 32), (1 / 32)⟩,
    ⟨(31 / 32), (1 / 1)⟩,
    ⟨(31 / 32), (1 / 1)⟩,
    ⟨(-1 / 32), (1 / 32)⟩,
    ⟨(-1 / 32), (1 / 32)⟩,
    ⟨(31 / 32), (1 / 1)⟩,
    ⟨(13 / 8), (425 / 256)⟩]

def certificate : IntervalCertificate 15 :=
  (.split 0 (0 / 1) (.split 2 (0 / 1) .reject (.split 4 (0 / 1) .reject .reject)) (.split 2 (0 / 1) (.split 4 (0 / 1) .reject .reject) .reject))

theorem accepted : certificate.check smallerFormula box = true := by
  decide +kernel

theorem statistics : certificate.nodeCount = 11 ∧ certificate.keptCount = 0 ∧
    certificate.rejectedCount = 6 ∧ certificate.depth = 3 := by
  decide +kernel

theorem localizes {x : Fin 15 → ℝ} (hx : box.Contains x) (hp : smallerFormula.Holds x) :
    ∃ C ∈ certificate.residuals box, C.Contains x :=
  certificate.check_sound smallerFormula accepted hx hp

theorem infeasible : ¬ ∃ x : Fin 15 → ℝ, box.Contains x ∧ smallerFormula.Holds x := by
  apply certificate.exclude_sound smallerFormula accepted
  exact List.length_eq_zero_iff.mp ((certificate.residuals_length box).trans statistics.2.1)

end ThreeSquares.GeneratedCertificates.RotatedOverlap6
