import ThreeSquares.WeightedSearch
import ThreeSquares.ContractedSyntax

-- Generated by GenerateCertificates.lean; kernel-checked data, not a global proof.
namespace ThreeSquares.GeneratedCertificates.Strengthened6

open PackingFormula

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

def box : RationalBox 15 :=
  ![⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-11 / 16), (11 / 16)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(-1 / 1), (1 / 1)⟩,
    ⟨(1 / 2), (425 / 256)⟩]

def certificate : IntervalCertificate 15 :=
  (.split 6 (0 / 1) (.split 7 (0 / 1) (.split 8 (0 / 1) (.split 9 (0 / 1) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep))) (.split 9 (0 / 1) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)))) (.split 8 (0 / 1) (.split 9 (0 / 1) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep))) (.split 9 (0 / 1) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep))))) (.split 7 (0 / 1) (.split 8 (0 / 1) (.split 9 (0 / 1) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep))) (.split 9 (0 / 1) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)))) (.split 8 (0 / 1) (.split 9 (0 / 1) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep))) (.split 9 (0 / 1) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep)) (.split 10 (0 / 1) (.split 11 (0 / 1) .keep .keep) (.split 11 (0 / 1) .keep .keep))))))

theorem accepted : certificate.check contractedFormula box = true := by
  decide +kernel

theorem statistics : certificate.nodeCount = 127 ∧ certificate.keptCount = 64 ∧
    certificate.rejectedCount = 0 ∧ certificate.depth = 6 := by
  decide +kernel

theorem localizes {x : Fin 15 → ℝ} (hx : box.Contains x) (hp : contractedFormula.Holds x) :
    ∃ C ∈ certificate.residuals box, C.Contains x :=
  certificate.check_sound contractedFormula accepted hx hp

end ThreeSquares.GeneratedCertificates.Strengthened6
