import ThreeSquares.WeightedSearch
import ThreeSquares.ContractedSyntax

-- Generated by GenerateCertificates.lean; kernel-checked data, not a global proof.
namespace ThreeSquares.GeneratedCertificates.Subcritical3

open PackingFormula

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

def box : RationalBox 15 :=
  ![⟨(-1 / 1), (0 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(1 / 4), (1 / 4)⟩,
    ⟨(-1 / 2), (-1 / 2)⟩,
    ⟨(1 / 4), (1 / 4)⟩,
    ⟨(1 / 2), (1 / 2)⟩,
    ⟨(1 / 1), (1 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(1 / 1), (1 / 1)⟩,
    ⟨(1 / 1), (1 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(0 / 1), (0 / 1)⟩,
    ⟨(1 / 1), (1 / 1)⟩,
    ⟨(13 / 8), (13 / 8)⟩]

def certificate : IntervalCertificate 15 :=
  (.split 0 (-1 / 2) (.split 0 (-3 / 4) .reject (.split 0 (-5 / 8) .keep .reject)) .reject)

theorem accepted : certificate.check smallerFormula box = true := by
  decide +kernel

theorem statistics : certificate.nodeCount = 7 ∧ certificate.keptCount = 1 ∧
    certificate.rejectedCount = 3 ∧ certificate.depth = 3 := by
  decide +kernel

theorem localizes {x : Fin 15 → ℝ} (hx : box.Contains x) (hp : smallerFormula.Holds x) :
    ∃ C ∈ certificate.residuals box, C.Contains x :=
  certificate.check_sound smallerFormula accepted hx hp

end ThreeSquares.GeneratedCertificates.Subcritical3
